#!/bin/bash

#The file is supposed to run in a specific directory hence the path to that directory has been stated

filepath="/Users/reginatenkorang/Desktop/Azubi_Projects/Linux/file_management"

#Checking if the directory does not exist, ! negates the result of the test and -d tests if the specified path is a diretory
if [ ! -d "$filepath" ]; then
     echo "Error: Directory does not exist."
     exit 1
fi



while true; do

    # Display menu options
    echo "File Manager Menu:"

    echo "1. Create a new file"

    echo "2. Delete an existing file"

    echo "3. List files in the directory"

    echo "4. Exit"
 
    read -p "Enter your choice (1-4): " user_input
 
    case $user_input in

        1)

            read -p "Enter the name of the new file: " new_file

            touch "$new_file"

            echo "'$new_file' created."

            ;;

        2)

            read -p "Enter the name of the file to delete: " del_file

            if [ -e "$del_file" ]; then

                rm "$del_file"

                echo "File '$del_file' deleted."

            else

                echo "Error:'$del_file' does not exist."

            fi

            ;;

        3)

            echo "Files in the directory:"

            ls

            ;;

        4)

            echo "Exiting the script"

            exit 0

            ;;
#Validate user's input by printing an error message if wrong input is received
         *)
            echo "Invalid choice. Please enter a number between 1 and 4."
            ;;

    esac
done
